stage: edge_classifier
model: InteractionGNN2WithPyG
input_dir: /pscratch/sd/p/pmtuan/2023_ttbar_uncorrelated/gfilter_13810901_epoch360_redo/ # Should contain the files used in training and inference
stage_dir: /global/cfs/cdirs/m2616/pmtuan/GNN4ITK/CommonFrameworkExamples/2023_ttbar_uncorrelated/gnn # A directory to be created that will store logs, artifacts, and output data
project: TTBAR_RETRAIN_WITH_IMPROVED_CONFIG # Used in logging
group: IGNN2_SILU_DETAILED_INPUT
gpus: 1
nodes: 1
precision: 16-mixed

# Dataset parameters
data_split: [7800, 1000, 1000] # Number of [training, validation, testing] examples
dataset_class: GraphDataset
undirected: False

# Truth and weighting parameters. Syntax is...
# Single value: track[key] == value
# List of 2 floats: value1 <= track[key] <= value2
# List with a string as the first value: First value defines the boolean test, the second value is a list or value. Boolean tests are: (in, not_in, is, is_not, within, not_within)
# All other tracks follow the default: If a true edge, weight=0. If a fake edge, weight=1.

input_cut: 0.15
weighting:
  - weight: 0.1
    conditions: 
      y: False
  - weight: 0.
    conditions:
      y: True
  - weight: 1.
    conditions:
      y: True
      pt: [1000, .inf]
      nhits: [3, .inf]
      primary: True
      pdgId: [not_in, [11, -11]]
      radius: [0., 260.]
      eta_particle: [-4., 4.]
      redundant_split_edges: False

# Model parameters
edge_cut: 0.5
node_features: [r, phi, z, eta, cluster_x_1, cluster_y_1, cluster_z_1, cluster_x_2, cluster_y_2, cluster_z_2, count_1, charge_count_1, count_2, charge_count_2]
node_scales: [1000., 3.14159265359, 1000., 1., 1000., 1000., 1000., 1000., 1000., 1000., 1,1,1,1]
edge_features: [dr, dphi, dz, deta]
hidden: 128
n_graph_iters: 8
n_node_encoder_layers: 3
n_edge_encoder_layers: 3
n_node_net_layers: 3
n_edge_net_layers: 3
n_node_decoder_layers: 3
n_edge_decoder_layers: 3
layernorm: False
batchnorm: True
bn_track_running_stats: False
hidden_activation: SiLU
output_activation: SiLU
edge_output_transform_final_activation: null
concat: true
node_net_recurrent: False
edge_net_recurrent: False
in_out_diff_agg: true
checkpointing: true

# Training parameters
warmup: 5
lr: 0.0005
min_lr: 0.000005
factor: 0.9
patience: 15
max_epochs: 1000
debug: false
num_workers: [8,8,8]
log_wandb: true
loss_balance: proportional

