stage: graph_construction
model: MetricLearning
input_dir: MY_DATA_DIR/data_reading
stage_dir: MY_DATA_DIR/metric_learning
project: ACAT2025_metric_leaarning
accelerator: cuda
devices: 1
nodes: 1

# Dataset parameters
data_split: [7785, 1000, 926]

hard_cuts: null

variable_with_prefix: true

# Truth and weighting parameters. Syntax is...
# Single value: track[key] == value
# List of 2 floats: value1 <= track[key] <= value2
# List with a string as the first value: First value defines the boolean test, the second value is a list or value. Boolean tests are: (in, not_in, is, is_not, within, not_within)
# All other tracks follow the default: If a true edge, weight=0. If a fake edge, weight=1.
weighting:
- weight: 1.0
  conditions:
    edge_y: false
- weight: 0.0
  conditions:
    edge_y: true
- weight: 4.0
  conditions:
    track_particle_nhits: [3, .inf]
    track_particle_pdgId: [not_in, [11, -11]]
    track_particle_primary: true
    track_particle_pt: [900, .inf]
    edge_y: true

# Model parameters
node_features: [hit_r, hit_phi, hit_z, hit_cluster_x_1, hit_cluster_y_1, hit_cluster_z_1, hit_cluster_x_2, hit_cluster_y_2, hit_cluster_z_2,
                hit_count_1, hit_charge_count_1, hit_loc_eta_1, hit_loc_phi_1,
                hit_localDir0_1, hit_localDir1_1, hit_localDir2_1, hit_lengthDir0_1, hit_lengthDir1_1, hit_lengthDir2_1,
                hit_glob_eta_1, hit_glob_phi_1, hit_eta_angle_1, hit_phi_angle_1,
                hit_count_2, hit_charge_count_2, hit_loc_eta_2, hit_loc_phi_2,
                hit_localDir0_2, hit_localDir1_2, hit_localDir2_2, hit_lengthDir0_2, hit_lengthDir1_2, hit_lengthDir2_2,
                hit_glob_eta_2, hit_glob_phi_2, hit_eta_angle_2, hit_phi_angle_2]
node_scales: [1000, 3.14, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
              1, 1, 3.14, 3.14,
              1, 1, 1, 1, 1, 1,
              3.14, 3.14, 3.14, 3.14,
              1, 1, 3.14, 3.14,
              1, 1, 1, 1, 1, 1,
              3.14, 3.14, 3.14, 3.14]
emb_dim: 12
emb_hidden: 1024
nb_layer: 4
activation: Tanh
r_train: 0.1
knn: 50
knn_val: 300
margin: 0.1
points_per_batch: 50000
train_undirected: true
undirected: true

lr: 0.001
warmup: 10
factor: 0.8
patience: 20
max_epochs: 1000
metric_mode: max
metric_to_monitor: f1
save_top_k: 1
scheduler: ReduceLROnPlateau
track_running_stats: false
randomisation: 1
precision: 32

event_prefix: ttbar_uncorr_pu200_v9