# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:
  - linting
  - pages
  - build
  - test
  - deploy

include:
  - ".gitlab/pipelines/.linting-gitlab-ci.yaml"
  - ".gitlab/pipelines/.pages-gitlab-ci.yaml"
  - ".gitlab/pipelines/.build-gitlab-ci.yaml"
  - ".gitlab/pipelines/.test-gitlab-ci.yaml"
  - ".gitlab/pipelines/.deploy-gitlab-ci.yaml"

