name: gnn4itk

channels:
    - pytorch
    - pyg
    - defaults
    - conda-forge
    
dependencies:
    - pip
    - numpy<=1.22
    - pandas
    - scipy
    - matplotlib
    - cpuonly
    - pytorch==1.10.2
    - pytorch-lightning=1.9.2
    - pyg
    - faiss-cpu