name: gnn4itk

channels:
    - pytorch
    - defaults
    - conda-forge

dependencies:
    - python=3.9
    - pip
    - numpy<=1.22
    - pandas
    - scipy
    - matplotlib
    - cpuonly
    - pytorch==1.12.1
    - pytorch-lightning=1.9.2
    - faiss-cpu
    - uproot
    - brevitas
    - qonnx
