name: gnn4itk-lasagna

channels:
    - rapidsai
    - nvidia
    - pytorch
    - conda-forge

dependencies:
    - python=3.9
    - pip
    - numpy<=1.22
    - pandas
    - scipy
    - matplotlib
    - cudf=22.08
    - cugraph=22.08
    - cudatoolkit=11.6
    - pytorch=1.12.1