# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: MY_DATA_DIR/ATLAS-P2-ITK-23-00-03_Rel.21.9/demo_ttbar/feature_store_ttbar_uncorr/
stage_dir: MY_DATA_DIR/ATLAS-P2-ITK-23-00-03_Rel.21.9/demo_ttbar/module_map_ttbar_uncorr/

# Dataset parameters
data_split: [10, 10, 10] # Number of [training, validation, testing] examples
module_map_path: MY_ACORN_DIR/model_store/MMtriplet_1GeV_3hits_noE__merged__sorted.txt
batch_size: 2000000

max_workers: 16