# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: MY_DATA_DIR/ATLAS-P2-ITK-23-00-03_Rel.21.9/ttbar/feature_store/
stage_dir: MY_DATA_DIR/ATLAS-P2-ITK-23-00-03_Rel.21.9/ttbar/module_map/

# Dataset parameters
data_split: [7800, 1000, 1000] # Number of [training, validation, testing] examples
module_map_path: MY_ACORN_DIR/model_store/module_map/MMtriplet_1GeV_3hits_noE__merged__sorted.txt
batch_size: 2000000

max_workers: 16

variable_with_prefix: true # Set to true to use the new naming scheme (with prefix to indicate the variable type)
add_variable_name_prefix: false # Set to true to convert old pyg files to using the new naming scheme (with prefix to indicate the variable type). Only needed when the input pyg files are without the name prefix.