# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: /scratch/bbhj/jareddb2/GNN4ITk/commonframework_data_output/uncorrelated2023/feature_store_08/
stage_dir: /scratch/bbhj/jareddb2/GNN4ITk/commonframework_data_output/uncorrelated2023/module_map/
num_workers: 0

# Dataset parameters
data_split: [80, 10, 10] # Number of [training, validation, testing] examples
module_map_path: /scratch/bbhj/GNN4ITk/Maps/CommonFramework/ATLASITk/MMtriplet_1GeV_3hits_noE__merged__sorted.txt
batch_size: 500000
