# CommonFramework configuration
stage: track_building
model: HierarchicalGNN
input_dir: /global/cfs/cdirs/m2616/pmtuan/inferred_data/igcn_14999421_epoch66_redo/ # Should contain the files used in training and inference
stage_dir: /global/cfs/cdirs/m3443/usr/ryanliu/HGNN/HGNN/ # A directory to be created that will store logs, artifacts, and output data
project: HGNN_example # Used in logging
gpus: 1
nodes: 1

# Dataset parameters
data_split: [1000, 100, 1000] # Number of [training, validation, testing] examples[7800, 1000, 1000]
data_config:
    edge_cut: 0.001
    loose_cut: 0.01
    tight_cut: 1.
    min_hits: 9
    random_drop: 0.
    signal_weight: 2
    signal_selection: 
        pt: [range, [1000, null]]
        eta: [range, [-4, 4]]
        primary: [isin, [1]]
        nhits: [range, [7, null]]
        pdgId: [notin, [11, -11]]
    target_selection:
        pt: [range, [1000, null]]
        nhits: [range, [3, null]]

node_features: [r, phi, z]
node_scales:   [1000, 3.14, 1000]
num_workers: [16, 16, 16]

# Loss Function
auxiliary_emb_steps: 3000
auxiliary_logit_steps: 3000
margin: 0.2

# Model Parameter
model_config:
    d_model: 128
    n_node_layers: 2
    n_edge_layers: 2
    n_output_layers: 5
    n_interaction_iterations: 6
    n_hierarchical_iterations: 8
    hidden_activation: GELU
    output_activation: null
    dropout: 0.
    emb_size: 8
    bsparsity: 8
    ssparsity: 5
    resolution: 1
    cut_momentum: 0.95
    min_size: 3

# Online Evaluation Parameter
metric_to_monitor: tracking_efficiency
score_cut: 0.8
matching_fraction: 0.5
matching_style: ATLAS
min_track_length: 5
selection:
    pt: [range, [1000, null]]
    eta: [range, [-4, 4]]
    primary: [isin, [1]]
    nhits: [range, [7, null]]
    pdgId: [notin, [11, -11]]
    
# Training config
warmup: null
lr: 0.004
factor: 0.9
patience: 5
max_epochs: 100