# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: MY_DATA_DIR/CHEP2023/data/
stage_dir: MY_DATA_DIR/CHEP2023/module_map/

# Dataset parameters
data_split: [1600, 80, 100] # Number of [training, validation, testing] examples
module_map_path: MY_DATA_DIR/CHEP2023/MM.df
batch_size: 2000000