# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: /sps/atlas/s/scaillou/CHEP2023/CTF_CHEP2023/data/
stage_dir: /sps/atlas/s/scaillou/CHEP2023/CTF_CHEP2023/module_map/

# Dataset parameters
data_split: [1600, 80, 100] # Number of [training, validation, testing] examples
module_map_path: /sps/l2it/scaillou/MM.df
batch_size: 2000000