stage: edge_classifier
model: InteractionGNN2
input_dir: /sps/l2it/scaillou/data/TEST_COMMON_FRAMEWORK/APPROVAL_SUMMER_2022/module_map/ # Should contain the files used in training and inference
stage_dir: /sps/l2it/scaillou/data/TEST_COMMON_FRAMEWORK/APPROVAL_SUMMER_2022/gnn/ # A directory to be created that will store logs, artifacts, and output data
project: APPROVAL_SUMMER_20022_GNN # Used in logging
gpus: 1
nodes: 1

# Dataset parameters
data_split: [397, 20, 100] # Number of [training, validation, testing] examples

# Truth and weighting parameters. Syntax is...
# Single value: track[key] == value
# List of 2 floats: value1 <= track[key] <= value2
# List with a string as the first value: First value defines the boolean test, the second value is a list or value. Boolean tests are: (in, not_in, is, is_not, within, not_within)
# All other tracks follow the default: If a true edge, weight=0. If a fake edge, weight=1.
weighting:
  - weight: 0.1
    conditions:
      y: False
  - weight: 0.0
    conditions:
      y: True
  - weight: 1.0
    conditions:
      y: True
      pt: [1000, .inf]
      nhits: [3, .inf]
      primary: True
      pdgId: [not_in, [11, -11]]

# Model parameters
edge_cut: 0.5
node_features: [r, phi, z]
edge_features: [dr, dphi, deta]
hidden: 128 
n_graph_iters: 8
n_node_encoder_layers: 2
n_edge_encoder_layers: 2
n_node_net_layers: 2
n_edge_net_layers: 2
n_node_decoder_layers: 2
n_edge_decoder_layers: 2
layernorm: True
batchnorm: False
bn_track_running_stats: False
hidden_activation: ReLU
output_activation: ReLU
edge_output_transform_final_activation: null
concat: True
node_net_recurrent: True
edge_net_recurrent: True
in_out_diff_agg: True
checkpointing: True

# Training parameters
warmup: 5
lr: 0.0005
factor: 0.9
patience: 15
max_epochs: 200