# CommonFramework configuration
stage: data_reading
model: AthenaReader
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed_2023paper/ttbar_correlated/all_events
stage_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed_2023paper/ttbar_correlated/feature_store_testing
module_lookup_path: /global/cfs/cdirs/m3443/data/ITk-upgrade/jan_files/ITKEvents4Paper2023/NewITkSamples_ttbar_test1/J101_0/Modules_geo.txt
max_workers: 32

# Feature Configurations
feature_sets:
    hit_features: [hit_id, x, y, z, r, phi, eta, region, 
                cluster_x_1, cluster_y_1, cluster_z_1, cluster_x_2, cluster_y_2, cluster_z_2, 
                norm_x, norm_y, norm_z_1, norm_z_2,
                count_1, charge_count_1, loc_eta_1, loc_phi_1, localDir0_1, localDir1_1, localDir2_1, lengthDir0_1, lengthDir1_1, lengthDir2_1, glob_eta_1, glob_phi_1, eta_angle_1, phi_angle_1,
                count_2, charge_count_2, loc_eta_2, loc_phi_2, localDir0_2, localDir1_2, localDir2_2, lengthDir0_2, lengthDir1_2, lengthDir2_2, glob_eta_2, glob_phi_2, eta_angle_2, phi_angle_2]
    track_features: [particle_id, pt, radius, primary, nhits, pdgId, redundant_split_edges]

region_labels:
    1: {hardware: PIXEL, barrel_endcap: -2}
    2: {hardware: STRIP, barrel_endcap: -2}
    3: {hardware: PIXEL, barrel_endcap: 0}
    4: {hardware: STRIP, barrel_endcap: 0}
    5: {hardware: PIXEL, barrel_endcap: 2}
    6: {hardware: STRIP, barrel_endcap: 2}

hard_cuts:

# Datatypes and Column Names (TODO: Move this into Python code, doesn't need to be configurable)
spacepoints_datatypes:
    cluster_index_1: int64
    cluster_index_2: int64
    hardware: str
    cluster_x_1: float32
    cluster_y_1: float32
    cluster_z_1: float32
    cluster_x_2: float32 
    cluster_y_2: float32 
    cluster_z_2: float32
    barrel_endcap: int32
    layer_disk: int32 
    eta_module: int32 
    phi_module: int32
    eta_angle_1: float32 
    phi_angle_1: float32 
    eta_angle_2: float32 
    phi_angle_2: float32
    norm_x: float32
    norm_y: float32
    norm_z_1: float32
    norm_z_2: float32
    
particles_datatypes:
    particle_id: int64
    subevent: int64
    barcode: int64
    px: float32
    py: float32
    pz: float32
    pt: float32
    eta: float32
    vx: float32
    vy: float32
    vz: float32
    radius: float32
    status: int32
    charge: float32
    pdgId: int32
    pass: str
    vProdNIn: int32
    vProdNOut: int32
    vProdStatus: int32
    vProdBarcode: int64

column_lookup:
    coordinates: [cluster_id, hardware, cluster_x, cluster_y, cluster_z]
    region: [barrel_endcap, layer_disk, eta_module, phi_module, side]
    norms: [norm_x, norm_y, norm_z]
    shape_a: [count, charge_count, loc_eta, loc_phi, localDir0, localDir1, localDir2, lengthDir0, lengthDir1, lengthDir2, glob_eta, glob_phi, eta_angle, phi_angle]
    shape_b: [eta_angle, phi_angle]