# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: /global/cfs/cdirs/m3443/data/GNN4ITK/CommonFrameworkExamples/Example_1_Dev/feature_store/ # Should contain the files used in training and inference
stage_dir: /global/cfs/cdirs/m3443/data/GNN4ITK/CommonFrameworkExamples/Example_1_Dev/module_map/ # A directory to be created that will store logs, artifacts, and output data

# Dataset parameters
data_split: [80, 10, 10] # Number of [training, validation, testing] examples
module_map_path: /global/cfs/cdirs/m3443/data/GNN4ITK/CommonFrameworkExamples/Example_1_Dev/example_1_module_map.csv