# build_docker:
#   stage: build
#   needs: []
#   variables:
#     TO: $CI_REGISTRY_IMAGE:latest
#     GIT_SSL_NO_VERIFY: "true"
#     DOCKER_FILE: Dockerfile
#   tags:
#     - docker-machine
#   script:
#     - ignore
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_COMMIT_TAG
#       variables:
#         TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# build_docker_test:
#   stage: build
#   needs: []
#   variables:
#     TO: '$CI_REGISTRY_IMAGE/temporary_images:${CI_COMMIT_REF_SLUG}-test'
#     GIT_SSL_NO_VERIFY: "true"
#     DOCKER_FILE: Dockerfile
#   tags:
#     - docker-machine
#   script:
#     - ignore

build_docker_test:
  stage: build
  needs: []
  tags:
  - docker-privileged-xl
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      variables:
        TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG