build_docker_test:
  stage: build
  needs: []
  tags:
  - docker-privileged-xl
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: "$CI_REGISTRY_IMAGE/temporary_images:${CI_COMMIT_REF_SLUG}-test"
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"
