run tests:
  stage: test
  needs: [build_docker_test]
  image: '$CI_REGISTRY_IMAGE/temporary_images:${CI_COMMIT_REF_SLUG}-test'
  script:
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
    - ls -la
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml