.graph_building_template: &graph_building_template
  stage: test
  tags:
    - k8s-gpu
  needs: []
  before_script:
    # Need to have acces to eos, so login with gnn4itk service account
    - echo "${gnn4itk_robot_psswd}" | kinit ${gnn4itk_robot_username}@CERN.CH
    - pwd
    - ls -la
    - yum install conda -y
    - conda init bash
    - source ~/.bashrc
    - conda config --set auto_activate_base false
    - source create_conda_environment_cu13.sh acorn-cu13
  rules:
    - when: always

PyModuleMap:
    <<: *graph_building_template
    script:
      - cd CI/graph_building
      - ./ci_test_graph_building_PyModuleMap.sh
