run tests:
  stage: test
  needs: [build_docker_test]
  image: '$CI_REGISTRY_IMAGE/temporary_images:${CI_COMMIT_REF_SLUG}-test'
  before_script:
    - apt-get update
    - apt-get install zip unzip
  script:
    - cd tests
    - ls -la
    - wget https://portal.nersc.gov/project/m3443/dtmurnane/GNN4ITk/TestData/test_files.zip 2>&1 >& /dev/null
    - ls -la
    - unzip test_files.zip 2>&1 >& /dev/null
    - source activate gnn4itk
    - which python
    - wandb disabled
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
    - ls -la
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: tests/coverage.xml
