stage: edge_classifier
model: InteractionGNN
input_dir: /scratch/bbhj/jareddb2/GNN4ITk/commonframework_data_output/uncorrelated2023/module_map/
stage_dir: /scratch/bbhj/jareddb2/GNN4ITk/commonframework_data_output/uncorrelated2023/gnn_noCut_1000events_h32_v2/
project: ttbar_uncorrelated_2023_full_GNN
gpus: 1
nodes: 1
num_workers: [8,8,8]

# Dataset parameters
data_split: [800, 100, 100] # Number of [training, validation, testing] examples

# All other tracks follow the default: If a true edge, weight=0. If a fake edge, weight=1.
weighting:
  - weight: 2.
    conditions:
      y: True
      pt: [1000, .inf]
      nhits: [3, .inf]
      primary: True
      pdgId: [not_in, [11, -11]]
      radius: [0., 260.]
      eta_particle: [-4., 4.]
      redundant_split_edges: False

# A list of hard cut conditions. Any hits not passing these conditions will be removed from the training and validation dataset.
# By definition, noise will not pass any of these cuts, so any hard cuts will remove noise.
hard_cuts: null

# Model parameters
edge_cut: 0.5
undirected: True
node_features: [r, phi, z]
node_scales:   [1000, 3.14, 1000]
hidden: 16
n_graph_iters: 8
nb_node_layer: 2
nb_edge_layer: 2
emb_channels: 0
layernorm: True
batchnorm: False
aggregation: [sum, mean, max, std]
hidden_activation: SiLU
output_activation: Tanh

# Training parameters
warmup: 5
lr: 0.001
factor: 0.9
patience: 10
max_epochs: 50
